// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKzyUubXg62iXqAeujmjvJSlv0V8qeqGg',
    appId: '1:628465738680:web:83f65142c3ac6c66f2254d',
    messagingSenderId: '628465738680',
    projectId: 'gotogetherapp-f80b0',
    authDomain: 'gotogetherapp-f80b0.firebaseapp.com',
    storageBucket: 'gotogetherapp-f80b0.firebasestorage.app',
    measurementId: 'G-8VNVDYJ7SK',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpkAmTGYN_PAGV9KIfqBGyNAQ66Gbzl0s',
    appId: '1:628465738680:android:3f029a8294ff329ff2254d',
    messagingSenderId: '628465738680',
    projectId: 'gotogetherapp-f80b0',
    storageBucket: 'gotogetherapp-f80b0.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcMaLu4zYVQ-rqRzqLWciiKfBjkF3oInQ',
    appId: '1:628465738680:ios:4ed4f8272dc4f687f2254d',
    messagingSenderId: '628465738680',
    projectId: 'gotogetherapp-f80b0',
    storageBucket: 'gotogetherapp-f80b0.firebasestorage.app',
    iosBundleId: 'com.ethanjrivera.goTogetherApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcMaLu4zYVQ-rqRzqLWciiKfBjkF3oInQ',
    appId: '1:628465738680:ios:4ed4f8272dc4f687f2254d',
    messagingSenderId: '628465738680',
    projectId: 'gotogetherapp-f80b0',
    storageBucket: 'gotogetherapp-f80b0.firebasestorage.app',
    iosBundleId: 'com.ethanjrivera.goTogetherApp',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKzyUubXg62iXqAeujmjvJSlv0V8qeqGg',
    appId: '1:628465738680:web:c176c9f10fb1a6ccf2254d',
    messagingSenderId: '628465738680',
    projectId: 'gotogetherapp-f80b0',
    authDomain: 'gotogetherapp-f80b0.firebaseapp.com',
    storageBucket: 'gotogetherapp-f80b0.firebasestorage.app',
    measurementId: 'G-KRZC6PECP4',
  );
}